# Generated by Django 4.0.3 on 2022-03-30 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='daftar_barang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('kode_inventaris', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='jenis_barang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_jenis', models.CharField(max_length=5)),
                ('nama_jenis', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='pinjam_barang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keterangan', models.TextField()),
                ('tgl_pinjam', models.DateTimeField(auto_now_add=True)),
                ('tgl_balik', models.DateTimeField(blank=True, null=True)),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinjam_stock.daftar_barang')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='daftar_barang',
            name='jenis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinjam_stock.jenis_barang'),
        ),
    ]
