# Generated by Django 4.0.3 on 2022-03-30 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinjam_stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinjam_barang',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
